### ISSUE TITLE
setParameters failed error

### ISSUE THREAD

**Issue by devgripes** [adityaarora1/LiveEdgeDetection#24]
I tried integrating the library in my project by adding the dependencies in both root gradle and app gradle file.

My config is:  
`compileSdk 28`
`minSdkVersion 21`
`targetSdkVersion 28`

I followed the usage guide which directs to a new Intent with the camera view and I got this error:

```
05-30 21:26:12.982 26179-26179/com.adityaarora.liveedgedetection E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.adityaarora.liveedgedetection, PID: 26179
    java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:1878)
        at com.adityaarora.liveedgedetection.view.ScanSurfaceView.surfaceChanged(ScanSurfaceView.java:137)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:594)
        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:606)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-30 21:26:28.387 26179-26185/com.adityaarora.liveedgedetection I/art: Debugger is no longer active
```

I also tried to compile the cloned repo and run it but still got the same error.
Any inputs about this?

Thanks!

**Comment by zakblacki** [comment]
Look at the previous issue someone fixed it

**Comment by adityaarora1** [comment]
Check latest version.
