### ISSUE TITLE
java.lang.RuntimeException: takePicture failed

### ISSUE THREAD

**Issue by anshdiv** [adityaarora1/LiveEdgeDetection#3]
04-13 12:45:29.958 19143-19143/com.adityaarora.liveedgedetection E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.adityaarora.liveedgedetection, PID: 19143
    java.lang.RuntimeException: takePicture failed
        at android.hardware.Camera.native_takePicture(Native Method)
        at android.hardware.Camera.takePicture(Camera.java:1543)
        at android.hardware.Camera.takePicture(Camera.java:1485)
        at com.adityaarora.liveedgedetection.view.ScanSurfaceView.autoCapture(ScanSurfaceView.java:313)
        at com.adityaarora.liveedgedetection.view.ScanSurfaceView.access$500(ScanSurfaceView.java:43)
        at com.adityaarora.liveedgedetection.view.ScanSurfaceView$3.onTick(ScanSurfaceView.java:296)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:133)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6205)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by codeteo** [comment]
I'm also having the same issue. Did you @anshdiv find any solution ? 

Thanks

**Comment by anshdiv** [comment]
Hello,

I have already contacted to aditya.He thought his code is error free,also
he is responding very rudely.

So its my advice to go with another solutions.

**Comment by aarora-infy** [comment]
@codeteo Please share your phone specs and error log.

**Comment by codeteo** [comment]
Device : Moto G (first generation)
OS Version: KitKat 4.4.4

04-16 17:34:21.081 28198-28198/com.adityaarora.liveedgedetection I/ScanSurfaceView: Preview Area 95%: 364800.0 Preview Area 20%: 76800.0 Area: 131046.0 Label: CAPTURING_IMAGE
04-16 17:34:21.083 28198-28198/com.adityaarora.liveedgedetection V/ScanSurfaceView: 1
04-16 17:34:21.119 28198-28198/com.adityaarora.liveedgedetection D/ScanSurfaceView: onPreviewFrame - received image 800x480
04-16 17:34:21.138 28198-28198/com.adityaarora.liveedgedetection I/ScanSurfaceView: previewWidth: 480.0
04-16 17:34:21.138 28198-28198/com.adityaarora.liveedgedetection I/ScanSurfaceView: previewHeight: 800.0
04-16 17:34:21.138 28198-28198/com.adityaarora.liveedgedetection I/ScanSurfaceView: Contour Area: 130562.0
04-16 17:34:21.138 28198-28198/com.adityaarora.liveedgedetection I/ScanSurfaceView: resultWidth: 272.0
04-16 17:34:21.138 28198-28198/com.adityaarora.liveedgedetection I/ScanSurfaceView: resultHeight: 486.0
04-16 17:34:21.139 28198-28198/com.adityaarora.liveedgedetection I/ScanUtils: ANGLES ARE:
04-16 17:34:21.139 28198-28198/com.adityaarora.liveedgedetection I/ScanUtils: 0.018232208179079848
04-16 17:34:21.139 28198-28198/com.adityaarora.liveedgedetection I/ScanUtils: 0.0074338805605962165
04-16 17:34:21.139 28198-28198/com.adityaarora.liveedgedetection I/ScanUtils: 0.010295969724281203
04-16 17:34:21.139 28198-28198/com.adityaarora.liveedgedetection I/ScanSurfaceView: GREEN(resultWidth/resultHeight) > 4: 0.5596707818930041 points[0].x == 0 && points[3].x == 0: 156.0: 165.0 points[2].x == previewHeight && points[1].x == previewHeight: 651.0: 637.0previewHeight: 800.0
04-16 17:34:21.140 28198-28198/com.adityaarora.liveedgedetection I/ScanSurfaceView: Preview Area 95%: 364800.0 Preview Area 20%: 76800.0 Area: 130562.0 Label: CAPTURING_IMAGE
04-16 17:34:21.195 28198-28211/com.adityaarora.liveedgedetection D/dalvikvm: GC_FOR_ALLOC freed 1824K, 46% free 9403K/17224K, paused 13ms, total 13ms
04-16 17:34:21.197 28198-28198/com.adityaarora.liveedgedetection V/ScanSurfaceView: 1
04-16 17:34:21.508 28198-28198/com.adityaarora.liveedgedetection V/ScanSurfaceView: 1
04-16 17:34:21.530 28198-28198/com.adityaarora.liveedgedetection D/AndroidRuntime: Shutting down VM
04-16 17:34:21.530 28198-28198/com.adityaarora.liveedgedetection W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41759d40)


`04-16 17:34:21.539 28198-28198/com.adityaarora.liveedgedetection E/AndroidRuntime: FATAL EXCEPTION: main
           Process: com.adityaarora.liveedgedetection, PID: 28198
           java.lang.RuntimeException: takePicture failed
               at android.hardware.Camera.native_takePicture(Native Method)
               at android.hardware.Camera.takePicture(Camera.java:1266)
               at android.hardware.Camera.takePicture(Camera.java:1211)
               at com.adityaarora.liveedgedetection.view.ScanSurfaceView.autoCapture(ScanSurfaceView.java:313)
               at com.adityaarora.liveedgedetection.view.ScanSurfaceView.access$500(ScanSurfaceView.java:43)
               at com.adityaarora.liveedgedetection.view.ScanSurfaceView$3.onTick(ScanSurfaceView.java:296)
               at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:124)
               at android.os.Handler.dispatchMessage(Handler.java:102)
               at android.os.Looper.loop(Looper.java:136)
               at android.app.ActivityThread.main(ActivityThread.java:5086)
               at java.lang.reflect.Method.invokeNative(Native Method)
               at java.lang.reflect.Method.invoke(Method.java:515)
               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
               at dalvik.system.NativeStart.main(Native Method)`


I'm also pasting some code  before the crash in case it helps - if you need anything else please ask me and I'll try to provide it.

Thanks!

**Comment by monowar1993** [comment]
Nexus 5
7.1.2 (LineageOS)

`
com.adityaarora.liveedgedetection E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.adityaarora.liveedgedetection, PID: 15481
    java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:2015)
        at com.adityaarora.liveedgedetection.view.ScanSurfaceView.surfaceChanged(ScanSurfaceView.java:130)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:630)
        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:161)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
`
Sample App is crashing.

**Comment by vinisauter** [comment]
FIXED in #5
@codeteo 
@anshdiv 
@monowar1993
