### ISSUE TITLE
App crash on latest Patch merge 

### ISSUE THREAD

**Issue by zakblacki** [adityaarora1/LiveEdgeDetection#37]
Stacktrace I don't know why this is happening 
this line is causing crash 

> //        Imgproc.Canny(originalMat, originalMat, ScanConstants.CANNY_THRESH_U, ScanConstants.CANNY_THRESH_L);

```
2020-01-20 02:10:49.948 23135-23135/? E/veedgedetectio: Unknown bits set in runtime_flags: 0x8000
2020-01-20 02:10:50.854 23135-23135/com.adityaarora.liveedgedetection E/veedgedetectio: No implementation found for void org.opencv.imgproc.Imgproc.Canny_3(long, long, double, double) (tried Java_org_opencv_imgproc_Imgproc_Canny_13 and Java_org_opencv_imgproc_Imgproc_Canny_13__JJDD)
2020-01-20 02:10:50.855 23135-23135/com.adityaarora.liveedgedetection E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.adityaarora.liveedgedetection, PID: 23135
    java.lang.UnsatisfiedLinkError: No implementation found for void org.opencv.imgproc.Imgproc.Canny_3(long, long, double, double) (tried Java_org_opencv_imgproc_Imgproc_Canny_13 and Java_org_opencv_imgproc_Imgproc_Canny_13__JJDD)
        at org.opencv.imgproc.Imgproc.Canny_3(Native Method)
        at org.opencv.imgproc.Imgproc.Canny(Imgproc.java:1104)
        at com.adityaarora.liveedgedetection.util.ScanUtils.detectLargestQuadrilateral(ScanUtils.java:359)
        at com.adityaarora.liveedgedetection.view.ScanSurfaceView$1.onPreviewFrame(ScanSurfaceView.java:182)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1221)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

**Comment by adityaarora1** [comment]
Check latest.
