### ISSUE TITLE
App Crashes on Camera Open

### ISSUE THREAD

**Issue by jatankshirsagar** [adityaarora1/LiveEdgeDetection#39]
java.lang.UnsatisfiedLinkError: No implementation found for void org.opencv.imgproc.Imgproc.Canny_3(long, long, double, double) (tried Java_org_opencv_imgproc_Imgproc_Canny_13 and Java_org_opencv_imgproc_Imgproc_Canny_13__JJDD)

 java.lang.UnsatisfiedLinkError: No implementation found for void org.opencv.imgproc.Imgproc.Canny_3(long, long, double, double) (tried Java_org_opencv_imgproc_Imgproc_Canny_13 and Java_org_opencv_imgproc_Imgproc_Canny_13__JJDD)
        at org.opencv.imgproc.Imgproc.Canny_3(Native Method)
        at org.opencv.imgproc.Imgproc.Canny(Imgproc.java:1104)
        at com.adityaarora.liveedgedetection.util.ScanUtils.detectLargestQuadrilateral(ScanUtils.java:359)
        at com.adityaarora.liveedgedetection.view.ScanSurfaceView$1.onPreviewFrame(ScanSurfaceView.java:182)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-02-01 18:12:45.429 1883-1883/com.jipl.storedge E/UncaughtException: java.lang.UnsatisfiedLinkError: No implementation found for void org.opencv.imgproc.Imgproc.Canny_3(long, long, double, double) (tried Java_org_opencv_imgproc_Imgproc_Canny_13 and Java_org_opencv_imgproc_Imgproc_Canny_13__JJDD)
        at org.opencv.imgproc.Imgproc.Canny_3(Native Method)
        at org.opencv.imgproc.Imgproc.Canny(Imgproc.java:1104)
        at com.adityaarora.liveedgedetection.util.ScanUtils.detectLargestQuadrilateral(ScanUtils.java:359)
        at com.adityaarora.liveedgedetection.view.ScanSurfaceView$1.onPreviewFrame(ScanSurfaceView.java:182)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by zakblacki** [comment]
You have to use older branch tree before the last update this one there is a bug
as workaround you have to enable the camera permission in your phone app 
or you add the permission in your code

**Comment by jatankshirsagar** [comment]
I am using it in Android and hence I am directly using implementation 'com.github.adityaarora1:LiveEdgeDetection:master-SNAPSHOT' and due to which how can I shift to the previous commit.

**Comment by zakblacki** [comment]
> I am using it in Android and hence I am directly using implementation 'com.github.adityaarora1:LiveEdgeDetection:master-SNAPSHOT' and due to which how can I shift to the previous commit.

[here ](https://github.com/adityaarora1/LiveEdgeDetection/commit/a32a3db35880ef286427315cba7ca318bbdc4178
)You can just restore theses 3 files he changed 

Edit : this crash only happen on android 5 and above. But works fine on android 4 
Few things to keep in mind : 

- The quality image taken sometimes suck (because the scan doesn't wait to set auto focus before taking picture) 
- This is only work dark background algorithm limitation 
- Auto scan need delay before taking picture 
- And it only works on portrait mode not landscape (Orientation angle)

In ScanUtils Activity he is not not calling theses  I suspect they may fix the orientation angle issue
determinePictureSize();
getDisplayOrientation();
getOptimalPreviewSize();
resize();

**Comment by jatankshirsagar** [comment]
java.lang.UnsatisfiedLinkError: No implementation found for void org.opencv.imgproc.Imgproc.Canny_3(long, long, double, double) (tried Java_org_opencv_imgproc_Imgproc_Canny_13 and Java_org_opencv_imgproc_Imgproc_Canny_13__JJDD)
        at org.opencv.imgproc.Imgproc.Canny_3(Native Method)
        at org.opencv.imgproc.Imgproc.Canny(Imgproc.java:1104)
        at com.adityaarora.liveedgedetection.util.ScanUtils.detectLargestQuadrilateral(ScanUtils.java:359)
        at com.adityaarora.liveedgedetection.view.ScanSurfaceView$1.onPreviewFrame(ScanSurfaceView.java:182)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-03-09 16:36:53.379 23155-23176/com.jipl.storedge I/m.jipl.storedg: Background concurrent copying GC freed 10827(587KB) AllocSpace objects, 3(60KB) LOS objects, 50% free, 15MB/31MB, paused 179us total 178.310ms
2020-03-09 16:36:53.698 23155-23155/com.jipl.storedge E/UncaughtException: java.lang.UnsatisfiedLinkError: No implementation found for void org.opencv.imgproc.Imgproc.Canny_3(long, long, double, double) (tried Java_org_opencv_imgproc_Imgproc_Canny_13 and Java_org_opencv_imgproc_Imgproc_Canny_13__JJDD)
        at org.opencv.imgproc.Imgproc.Canny_3(Native Method)
        at org.opencv.imgproc.Imgproc.Canny(Imgproc.java:1104)
        at com.adityaarora.liveedgedetection.util.ScanUtils.detectLargestQuadrilateral(ScanUtils.java:359)
        at com.adityaarora.liveedgedetection.view.ScanSurfaceView$1.onPreviewFrame(ScanSurfaceView.java:182)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)


Android Device : One Plus 3
Os Version : 9

after making changes in the file getting the above error

**Comment by DerrickRocha** [comment]
I keep seeing this error as well. Is there a work around yet?

**Comment by ka05** [comment]
@jatankshirsagar, @DerrickRocha, @zakblacki I have been able to fix this by updating the OpenCV version from 340 to 343. I have created [PR #42](https://github.com/adityaarora1/LiveEdgeDetection/pull/42)

**Comment by ka05** [comment]
@jatankshirsagar, @DerrickRocha, @zakblacki I have been able to fix this by updating the OpenCV version from 340 to 343. I have created [PR #42](https://github.com/adityaarora1/LiveEdgeDetection/pull/42)

**Comment by adityaarora1** [comment]
Should work now.
