### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by Mehedi50200** [adityaarora1/LiveEdgeDetection#6]
after building the app without any changes the app is being stopped when capturing the picture. So i tried the sample app you provided. It did the same thing with two different devices (Galaxy S4, Galaxy Note 3) along with Pixel 2 (emulator)

**Comment by abhatnagar03** [comment]
Please provide crash details (stacktrace)

**Comment by Mehedi50200** [comment]
java.lang.RuntimeException: takePicture failed
                      at android.hardware.Camera.native_takePicture(Native Method)
                      at android.hardware.Camera.takePicture(Camera.java:1507)
                      at android.hardware.Camera.takePicture(Camera.java:1452)
                      at com.adityaarora.liveedgedetection.view.ScanSurfaceView.autoCapture(ScanSurfaceView.java:313)
                      at com.adityaarora.liveedgedetection.view.ScanSurfaceView.access$500(ScanSurfaceView.java:43)
                      at com.adityaarora.liveedgedetection.view.ScanSurfaceView$3.onTick(ScanSurfaceView.java:296)
                      at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:133)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:145)
                      at android.app.ActivityThread.main(ActivityThread.java:6912)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by nbonatsakis** [comment]
@abhatnagar03 I'm seeing this as well on API 28, Essential phone. Any thoughts on what this could be?

**Comment by Mehedi50200** [comment]
Add 
android:largeHeap="true"
In the manifest, it will solve the problem. Atleast it did for me. 😊

**Comment by manishakamble** [comment]
The application gets crashed after installing on Samsung mobile. please see below the crash details
`java.lang.UnsatisfiedLinkError: No implementation found for void org.opencv.imgproc.Imgproc.Canny_4(long, long, double, double) (tried Java_org_opencv_imgproc_Imgproc_Canny_14 and Java_org_opencv_imgproc_Imgproc_Canny_14__JJDD)
        at org.opencv.imgproc.Imgproc.Canny_4(Native Method)
        at org.opencv.imgproc.Imgproc.Canny(Imgproc.java:2766)
        at com.adityaarora.liveedgedetection.util.ScanUtils.detectLargestQuadrilateral(ScanUtils.java:359)
        at com.adityaarora.liveedgedetection.view.ScanSurfaceView$1.onPreviewFrame(ScanSurfaceView.java:182)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1225)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)`

**Comment by adityaarora1** [comment]
Please check the latest version and create an issue if it still persists.
